### ISSUE TITLE
Add filter for tags

### ISSUE THREAD

**Issue by e-wu** [sara-sabr/rp-azuredevops-roadmaps#18]
Allow filtering on tags

**Comment by marinierb** [comment]
- Filter everything in the view
- Ability to select multiple tags

**Comment by marinierb** [comment]
Multiple tags is an "or". Maybe have to choice of "and" or "or". The way Delivery Plans does it.

**Comment by e-wu** [comment]
Filter that have:
- Any tag
- All tags
- Top level any tag
- Top level all tags
